[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "tesseract4", "ghostscript", "unpaper"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python ws_server.py"
